openapi: 3.0.1
info:
  title: net-sync-tasker
  description: basic template for map colonies service
  version: 1.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /generateTasks:
    post:
      operationId: generateTasks
      tags:
        - TaskGenerator
      summary: creates batched tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createTasksPayload'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    createTasksPayload:
      type: object
      required:
        - jobId
        - resourceId
        - resourceVersion
        - layerRelativePath
      properties:
        jobId:
          type: string
          format: uuid
        resourceId:
          type: string
        resourceVersion:
          type: string
        layerRelativePath:
          type: string
