{{- $chartName := include "net-sync-tasker.name" . -}}
{{- $tracingUrl := include "net-sync-tasker.tracingUrl" . -}}
{{- $metricsUrl := include "net-sync-tasker.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  BATCH_SIZE: {{ .Values.env.batchSize | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote}}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.resetTimeout | quote }}
  SERVICE_CLIENTS_CATALOG_URL: {{ .Values.env.serviceClients.catalog.url | quote}}
  SERVICE_CLIENTS_JOB_MANAGER_URL: {{ .Values.env.serviceClients.jobManager.url | quote }}
  SERVICE_CLIENTS_TASK_TYPE: {{ .Values.env.serviceClients.jobManager.taskType | quote }}
{{- end }}
