{{- $releaseName := .Release.Name -}}
{{- $chartName := include "net-sync-tasker.name" . -}}
{{- $cloudProviderFlavor := include "net-sync-tasker.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "net-sync-tasker.cloudProviderDockerRegistryUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "net-sync-tasker.environment" . }}
    release: {{ $releaseName }}
    {{- include "net-sync-tasker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "net-sync-tasker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "net-sync-tasker.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.cloudProvider.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
