global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30037 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

image:
  repository: net-sync-tasker
  imagePullSecretName: 'my-registry-secret'
  tag: 'latest'

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: warn
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  batchSize: 1000
  httpRetry:
    attempts: 3
    delay: 'exponential'
    resetTimeout: true
  serviceClients:
    catalog:
      url: http://localhost:30019
    jobManager:
      url: http://localhost:30010
      taskType: tilesSync

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  host:
  path: /

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
